apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: backupscheduleds.extension.shepherd
spec:
  group: extension.shepherd
  names:
    kind: BackupScheduled
    plural: backupscheduleds
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            mysql:
              description: MySQL databases which will be backed up.
              type: object
            schedule:
              description: Schedule is the crontab statement which defines how often
                a backup should run.
              properties:
                concurrencyPolicy:
                  description: 'Specifies how to treat concurrent executions of a
                    Job. Valid values are: - "Allow" (default): allows CronJobs to
                    run concurrently; - "Forbid": forbids concurrent runs, skipping
                    next run if previous run hasn''t finished yet; - "Replace": cancels
                    currently running job and replaces it with a new one'
                  type: string
                crontab:
                  description: The schedule in Cron format, see https://en.wikipedia.org/wiki/Cron.
                  type: string
                failedJobsHistoryLimit:
                  description: The number of failed finished jobs to retain. This
                    is a pointer to distinguish between explicit zero and not specified.
                  format: int32
                  type: integer
                startingDeadlineSeconds:
                  description: Optional deadline in seconds for starting the job if
                    it misses scheduled time for any reason.  Missed jobs executions
                    will be counted as failed ones.
                  format: int64
                  type: integer
                successfulJobsHistoryLimit:
                  description: The number of successful finished jobs to retain. This
                    is a pointer to distinguish between explicit zero and not specified.
                  format: int32
                  type: integer
                suspend:
                  description: This flag tells the controller to suspend subsequent
                    executions, it does not apply to already started executions.  Defaults
                    to false.
                  type: boolean
              required:
              - crontab
              type: object
            volumes:
              description: Volumes which will be backed up.
              type: object
          required:
          - schedule
          type: object
        status:
          properties:
            active:
              description: A list of pointers to currently running jobs.
              items:
                type: object
              type: array
            lastExecutedTime:
              description: Information when was the last time the job was successfully
                scheduled.
              format: date-time
              type: string
          type: object
  version: v1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
