apiVersion: extension.shepherd/v1
kind: BackupScheduled
metadata:
  name: node-123-backup-xyz
  labels:
    site: "456"
    environment: "123"
spec:
  schedule:
    crontab: "32 11 * * *"
    startingDeadlineSeconds: 86400
    concurrencyPolicy: "Forbid"
    suspend: false
  volumes:
    shared:
      claimName: node-123-shared
  mysql:
    default:
      secret:
        name: node-123
        keys:
          username: DATABASE_USER
          password: DATABASE_PASSWORD
          database: DATABASE_NAME
          hostname: DATABASE_HOST
          port: DATABASE_PORT
status:
  lastExecutedTime: '2018-11-21T00:16:43Z'

